/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "bsp_diag_uart.h"
#include "Delay.h"

#define FRONT_PWMA_PIN  GPIO_Pin_2
#define FRONT_PWMB_PIN  GPIO_Pin_3
#define FRONT_AIN1_PIN  GPIO_Pin_2
#define FRONT_AIN2_PIN  GPIO_Pin_3
#define FRONT_BIN1_PIN  GPIO_Pin_4
#define FRONT_BIN2_PIN  GPIO_Pin_5
#define FRONT_STBY_PIN  GPIO_Pin_6
#define REAR_LEFT_EN_PIN   GPIO_Pin_6
#define REAR_RIGHT_EN_PIN  GPIO_Pin_7
#define REAR_LEFT_IN1_PIN  GPIO_Pin_6
#define REAR_LEFT_IN2_PIN  GPIO_Pin_1
#define REAR_RIGHT_IN1_PIN GPIO_Pin_9
#define REAR_RIGHT_IN2_PIN GPIO_Pin_7

int main(void)
{
    GPIO_InitTypeDef gpio;

    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA |
                           RCC_APB2Periph_GPIOC |
                           RCC_APB2Periph_GPIOE |
                           RCC_APB2Periph_GPIOG,
                           ENABLE);

    /* Direct GPIO enable: bypass TIM2/PWM and the motor driver module. */
    gpio.GPIO_Pin = FRONT_PWMA_PIN | FRONT_PWMB_PIN |
                    REAR_LEFT_EN_PIN | REAR_RIGHT_EN_PIN;
    gpio.GPIO_Mode = GPIO_Mode_Out_PP;
    gpio.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_Init(GPIOA, &gpio);

    gpio.GPIO_Pin = FRONT_AIN1_PIN | FRONT_AIN2_PIN |
                    FRONT_BIN1_PIN | FRONT_BIN2_PIN |
                    FRONT_STBY_PIN | REAR_RIGHT_IN1_PIN |
                    REAR_RIGHT_IN2_PIN;
    GPIO_Init(GPIOE, &gpio);

    gpio.GPIO_Pin = REAR_LEFT_IN1_PIN;
    GPIO_Init(GPIOC, &gpio);

    gpio.GPIO_Pin = REAR_LEFT_IN2_PIN;
    GPIO_Init(GPIOG, &gpio);

    GPIO_ResetBits(GPIOA, FRONT_PWMA_PIN | FRONT_PWMB_PIN |
                          REAR_LEFT_EN_PIN | REAR_RIGHT_EN_PIN);
    GPIO_ResetBits(GPIOE, FRONT_AIN1_PIN | FRONT_AIN2_PIN |
                          FRONT_BIN1_PIN | FRONT_BIN2_PIN |
                          FRONT_STBY_PIN | REAR_RIGHT_IN1_PIN |
                          REAR_RIGHT_IN2_PIN);
    GPIO_ResetBits(GPIOC, REAR_LEFT_IN1_PIN);
    GPIO_ResetBits(GPIOG, REAR_LEFT_IN2_PIN);

    DiagUart_Init(115200U);
    DiagUart_WriteString("wheel_direction.begin LF,RF,LR,RR each FWD then REV\r\n");

    Delay_ms(2000U);

    while (1)
    {
    DiagUart_WriteString("wheel_direction.cycle_begin\r\n");

    /* TB6612 enabled; each front PWM input is selected independently. */
    GPIO_SetBits(GPIOE, FRONT_STBY_PIN);

    /* Left front forward: AIN1=1, AIN2=0. */
    GPIO_SetBits(GPIOA, FRONT_PWMA_PIN);
    DiagUart_WriteString("wheel.LF IN1=1 IN2=0\r\n");
    GPIO_SetBits(GPIOE, FRONT_AIN1_PIN);
    GPIO_ResetBits(GPIOE, FRONT_AIN2_PIN |
                          FRONT_BIN1_PIN | FRONT_BIN2_PIN);
    Delay_ms(2000U);

    GPIO_ResetBits(GPIOE, FRONT_AIN1_PIN | FRONT_AIN2_PIN);
    Delay_ms(1000U);

    /* Left front reverse: AIN1=0, AIN2=1. */
    DiagUart_WriteString("wheel.LF IN1=0 IN2=1\r\n");
    GPIO_ResetBits(GPIOE, FRONT_AIN1_PIN);
    GPIO_SetBits(GPIOE, FRONT_AIN2_PIN);
    Delay_ms(2000U);

    GPIO_ResetBits(GPIOE, FRONT_AIN1_PIN | FRONT_AIN2_PIN);
    GPIO_ResetBits(GPIOA, FRONT_PWMA_PIN);
    Delay_ms(2000U);

    /* Right front forward: BIN1=1, BIN2=0. */
    GPIO_SetBits(GPIOA, FRONT_PWMB_PIN);
    DiagUart_WriteString("wheel.RF IN3=1 IN4=0\r\n");
    GPIO_SetBits(GPIOE, FRONT_BIN1_PIN);
    GPIO_ResetBits(GPIOE, FRONT_BIN2_PIN |
                          FRONT_AIN1_PIN | FRONT_AIN2_PIN);
    Delay_ms(2000U);

    GPIO_ResetBits(GPIOE, FRONT_BIN1_PIN | FRONT_BIN2_PIN);
    Delay_ms(1000U);

    /* Right front reverse: BIN1=0, BIN2=1. */
    DiagUart_WriteString("wheel.RF IN3=0 IN4=1\r\n");
    GPIO_ResetBits(GPIOE, FRONT_BIN1_PIN);
    GPIO_SetBits(GPIOE, FRONT_BIN2_PIN);
    Delay_ms(2000U);

    GPIO_ResetBits(GPIOE, FRONT_BIN1_PIN | FRONT_BIN2_PIN);
    GPIO_ResetBits(GPIOA, FRONT_PWMB_PIN);
    Delay_ms(2000U);

    /* Left rear first polarity: PC6=1, PG1=0. */
    GPIO_SetBits(GPIOA, REAR_LEFT_EN_PIN);
    DiagUart_WriteString("wheel.LR IN1=1 IN2=0\r\n");
    GPIO_SetBits(GPIOC, REAR_LEFT_IN1_PIN);
    GPIO_ResetBits(GPIOG, REAR_LEFT_IN2_PIN);
    Delay_ms(2000U);

    GPIO_ResetBits(GPIOC, REAR_LEFT_IN1_PIN);
    GPIO_ResetBits(GPIOG, REAR_LEFT_IN2_PIN);
    Delay_ms(1000U);

    /* Left rear opposite polarity: PC6=0, PG1=1. */
    DiagUart_WriteString("wheel.LR IN1=0 IN2=1\r\n");
    GPIO_ResetBits(GPIOC, REAR_LEFT_IN1_PIN);
    GPIO_SetBits(GPIOG, REAR_LEFT_IN2_PIN);
    Delay_ms(2000U);

    GPIO_ResetBits(GPIOA, REAR_LEFT_EN_PIN);
    GPIO_ResetBits(GPIOC, REAR_LEFT_IN1_PIN);
    GPIO_ResetBits(GPIOG, REAR_LEFT_IN2_PIN);
    Delay_ms(2000U);

    /* Right rear first polarity: PE9=1, PE7=0. */
    GPIO_SetBits(GPIOA, REAR_RIGHT_EN_PIN);
    DiagUart_WriteString("wheel.RR IN3=1 IN4=0\r\n");
    GPIO_SetBits(GPIOE, REAR_RIGHT_IN1_PIN);
    GPIO_ResetBits(GPIOE, REAR_RIGHT_IN2_PIN);
    Delay_ms(2000U);

    GPIO_ResetBits(GPIOE, REAR_RIGHT_IN1_PIN | REAR_RIGHT_IN2_PIN);
    Delay_ms(1000U);

    /* Right rear opposite polarity: PE9=0, PE7=1. */
    DiagUart_WriteString("wheel.RR IN3=0 IN4=1\r\n");
    GPIO_ResetBits(GPIOE, REAR_RIGHT_IN1_PIN);
    GPIO_SetBits(GPIOE, REAR_RIGHT_IN2_PIN);
    Delay_ms(2000U);

    GPIO_ResetBits(GPIOA, FRONT_PWMA_PIN | FRONT_PWMB_PIN |
                          REAR_LEFT_EN_PIN | REAR_RIGHT_EN_PIN);
    GPIO_ResetBits(GPIOE, FRONT_AIN1_PIN | FRONT_AIN2_PIN |
                          FRONT_BIN1_PIN | FRONT_BIN2_PIN |
                          FRONT_STBY_PIN | REAR_RIGHT_IN1_PIN |
                          REAR_RIGHT_IN2_PIN);
    GPIO_ResetBits(GPIOC, REAR_LEFT_IN1_PIN);
    GPIO_ResetBits(GPIOG, REAR_LEFT_IN2_PIN);
    DiagUart_WriteString("wheel_direction.cycle_end all=LOW pause=3000ms\r\n");
    Delay_ms(3000U);
    }
}
